language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls
# command to run tests
script:
  coverage run --source=openbrokerapi ./setup.py test
after_success:
  coveralls